import './globals.css';

import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import AppFooter from '@/components/layout/app-footer';
import AppHeader from '@/components/layout/app-header';
import ProviderContainer from '@/components/providers';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased pt-16 flex flex-col min-h-screen`}>
        <ProviderContainer>
          <AppHeader />
          <main className="flex-1 w-full max-w-7xl mx-auto">
            {children}
          </main>
          <AppFooter />
        </ProviderContainer>
      </body>
    </html>
  );
}
